version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - '5000:5000'

  products_db:
    container_name: postgres_db
    image: postgres:14
    restart: always
    networks:
      - backend
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  orders_db:
    container_name: orders_db
    image: mongo:5
    restart: always
    networks:
      - backend
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  users_db:
    container_name: users_db
    image: mongo:5
    restart: always
    networks:
      - backend
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    networks:
      - backend
    ports:
      - '5672:5672'
      - '15672:15672'

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    networks:
      - backend
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    networks:
      - backend
    ports:
      - '3000:3000'
    environment:
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
      - GF_ADMIN_USER=grafana
      - GF_ADMIN_PASSWORD=grafana
    depends_on:
      - prometheus

networks:
  backend:
