spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/products/**
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**

server:
  port: 5000

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java:
      version: @java.version@

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: localhost
