spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: products-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/products/**

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec-eureka:8761/eureka/
  instance:
    hostname: ec-gateway
