spring:
  application:
    name: eureka

server:
  port: 8761

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java:
      version: @java.version@

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
