spring:
  application:
    name: eureka-service

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false